config/routes.rb
Harmony::Application.routes.draw do
  resources :users

  resources :images

  get "statics/home"
  root :to =>"statics#home"

  resources :blog_posts#, :as=>"blog"

  

  resources :pages#, :path => ''

  resources :events
  resources :sessions, :only => [:new, :create, :destroy]
  
  
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  
  

 
  
  
  
  

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  before_save :erase_link!
  before_update :erase_link!

  validates :body, :presence => true

  def erase_link!
    self.media=self.media.gsub(/<a.*><img/i, "<img").gsub('</a>', '')
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.order("created_at DESC")
    @title="Blog"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @blog_posts }
    end
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @blog_post }
    end
  end

  # GET /blog_posts/new
  # GET /blog_posts/new.json
  def new
    @blog_post = BlogPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @blog_post }
    end
  end

  # GET /blog_posts/1/edit
  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(params[:blog_post])

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to blog_posts_url, :notice => 'Blog post was successfully created.' }
        format.json { render :json => blog_posts_url, :status => :created, :location => @blog_post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @blog_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blog_posts/1
  # PUT /blog_posts/1.json
  def update
    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      if @blog_post.update_attributes(params[:blog_post])
        format.html { redirect_to blog_posts_url, :notice => 'Blog post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @blog_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Video_or_Photo_embed_codes %><br />
    <%= f.text_field :media %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing blog_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<center>	 	<% if signed_in? %><br /><%= link_to 'New Blog post', new_blog_post_path %><% end %></center><br />
<div class="cal">
<% @blog_posts.each_with_index do |blog_post, index| %>

  <% if index==0%>
		<div class="cal-text top-round">
	<% elsif index==@blog_posts.count-1%>
		<div class="cal-text bottom-round">
	<% else %>
			<div class="cal-text">
	<%end%>
	
	<center><%= blog_post.media.html_safe%></center>
	<p><%= simple_format(blog_post.body) %></p>
	<p>Posted <%= time_ago_in_words(blog_post.created_at) %> ago.</p>
	 	<% if signed_in? %>
   <%= link_to 'Edit', edit_blog_post_path(blog_post) %>
   <%= link_to 'Delete', blog_post, :confirm => 'Are you sure?', :method => :delete %>
		<% end %>
	<% if index!=@blog_posts.count-1%>
		<div class="bar"></div>
		<% end %>
</div>
	
	

   
<% end %>
</div>

app/views/blog_posts/new.html.erb
<h1>New blog_post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Media:</b>
  <%= @blog_post.media %>
</p>

<p>
  <b>Body:</b>
  <%= @blog_post.body %>
</p>


<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>