config/routes.rb
Harmony::Application.routes.draw do
  resources :users

  resources :images

  get "statics/home"
  root :to =>"statics#home"

  resources :blog_posts#, :as=>"blog"

  

  resources :pages#, :path => ''

  resources :events
  resources :sessions, :only => [:new, :create, :destroy]
  
  
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  
  

 
  
  
  
  

end

app/models/image.rb
class Image < ActiveRecord::Base
  before_save :erase_link!
  before_update :erase_link!
  
  validates :hotlink, :presence => true
  
  def erase_link!
    self.hotlink=self.hotlink.gsub(/<a.*><img/i, "<img").gsub('</a>', '')
  end
  def small
    self.hotlink.gsub(".jpg", "_m.jpg").gsub(/width=".*" height=".*" /i, "")
  end
  
  def location
    self.hotlink.gsub(/<img src="/i, "").gsub(/.jpg" .+/i, ".jpg")
  end
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
    @images = Image.order("created_at DESC")
    @title="Gallery"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to images_url, :notice => 'Image was successfully created.' }
        format.json { render :json => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.json { render :json => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to images_url, :notice => 'Image was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :ok }
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
 
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hotlink %><br />
    <%= f.text_field :hotlink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<script>
$(document).ready(function() {
		$(".single_image").fancybox({
			'transitionIn' : 'fade',
			'transitionOut' : 'fade',
		});
	});
</script>
 	
	<% if signed_in? %>
		<p>Copy and paste the code from the Make Music Flickr in here! Use the default size (Medium 500).</p>
		<center>	
			<%= link_to 'New Image', new_image_path %>
		</center>
	<% end %>

<br />
<div id="gal-cover">
<% @images.each do |image| %>

<div class="crop">
	<% if signed_in? %><%= link_to 'X', image, :confirm => 'Are you sure?', :method => :delete, :class=> :delete %><% end %>
<div class="gal">
	<div class="overflow">
 		<%= link_to "#{image.small}".html_safe, "#{image.location}", :class => "single_image", :href=>"#{image.location}" %>
	</div>
<br />
   
</div>
 
</div>

<% end %>
</div>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

 
<div class="center"><%= @image.hotlink.html_safe%></div>